making /en build first, and updating copies in an attempt to minimize build time

diff --git a/build-php-gtk-manual b/build-php-gtk-manual
--- a/build-php-gtk-manual
+++ b/build-php-gtk-manual
@@ -17,8 +17,19 @@ echo -n ">>> starting build at: "
 date
 
 echo ">>> making work directory ... "
-cp -r $PHPDOC $DIR
+cp -R -u $PHPDOC $DIR
 cd $DIR || exit 1
+
+#
+# only files that have been translated are utf-8 converted during
+# ./configure, therefore the en ./configure needs to be run before any
+# of the others are (else cs and de makes will fail, assuming they run
+# in alphabetical order).
+# NB en doesn't need to be make'd at this point and won't do all the
+# work twice, so long as autoconf isn't called twice.  ..
+#
+echo ">>> running base ./configure (en) "
+./configure || exit 1
 
 echo ">>> running ./configure --with-lang=$LANG ... "
 ./configure --with-lang=$LANG || exit 1
